
title: My Adventures of Coding
author: Xagon
email: DevXagon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
In this Blog you will be able to experience my adventures of Coding with me. Lets see, where it will take us next. 

# social links
twitter_username: none for now. # DO NOT include the @ character, or else the build will fail!
github_username:  Dev-Xagon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
