title: The Adventures of Coding
author: DevXagon
email: DevXagon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Let me take you with me on my adventures of coding C++ in Unreal Engine from Beginner to useful person. I will try to get to a point where I am able to create useful AR Applications in Unreal Engine.

# social links

github_username:  Dev-Xagon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
